var details = [
    data1 = {
        title: "testing issue number one test ichi",
        date: "2020-11-25",
        Help_topic: "PAY VIA QR",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 10pm"
    },
    data2 = {
        title: "testing issue number two test ni",
        date: "2020-11-24",
        Help_topic: "ACCOUNT BILLING",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 9pm"
    },
    data3 = {
        title: "testing issue number three test san",
        date: "2017-03-09",
        Help_topic: "REGISTRATION",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 8pm"
    },
    data4 = {
        title: "testing issue number four test yon",
        date: "2017-03-09",
        Help_topic: "PAY VIA QR",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 7pm"
    },
    data5 = {
        title: "testing issue number five test go",
        date: "2017-03-07",
        Help_topic: "PAY VIA QR",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 6pm"
    },
    data6 = {
        title: "testing issue number six test roku",
        date: "2017-03-10",
        Help_topic: "ACCOUNT BILLING",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 5pm"
    },
    data7 = {
        title: "testing issue number seven test nana",
        date: "2017-03-09",
        Help_topic: "REGISTRATION",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 4pm"
    },
    data8 = {
        title: "testing issue number eight test hachi",
        date: "2017-03-09",
        Help_topic: "PAY VIA QR",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 3pm"
    },
    data9 = {
        title: "testing issue number nine test kyuu",
        date: "2017-03-09",
        Help_topic: "PAY VIA QR",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 2pm"
    },
    data10 = {
        title: "testing issue number ten test juu",
        date: "2020-11-24",
        Help_topic: "ACCOUNT BILLING",
        status: "Open",
        name: "mary An Camarador",
        Mobile_no: "0917311728790",
        IMEI: "9898786",
        email: "Maryon.comarador@optimumdataventures.com",
        department: "GK Accounting",
        assigned_To: "Mira Coson(MIRA_01)",
        last_reply: "today at 1pm"
    }
]